# Use a Python base image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc

# Copy the requirements file and install dependencies
COPY ./agent/requirements.txt .
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the rest of the agent code
COPY . /app



# Expose the port for the ADK web interface
EXPOSE 8000

# Command to run the ADK agent with the web interface
CMD ["adk", "web", "--host", "0.0.0.0"]