# main.tf

# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "travel-global-lb-frontend" {
  source        = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v14.2.0"
  name          = "lb-frontend"
  project_id    = "n26-learn-c2c-app-dev-1"
  url_map_input = module.travel-global-lb-backend.backend_service_info
}

module "travel-global-lb-backend" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v13.2.0"
  name       = "lb-backend"
  project_id = "n26-learn-c2c-app-dev-1"
  serverless_neg_backends = [{
    region          = module.travel-frontend-service.location
    service_name    = module.travel-frontend-service.service_name
    service_version = ""
    type            = "cloud-run"
  }]
}

module "travel-frontend-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.25.0"
  project_id                    = "n26-learn-c2c-app-dev-1"
  location                      = "us-central1"
  service_name                  = "frontend"
  containers                    = [{"env_vars" = {"travel_backend_service_SERVICE_ENDPOINT" = module.travel-backend-service.service_uri}, "ports" = {"container_port" = 8080}, "container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/run.invoker"]
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}

module "travel-backend-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.25.0"
  project_id                    = "n26-learn-c2c-app-dev-1"
  location                      = "us-central1"
  service_name                  = "root-agent"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"travel_database_secret_SECRET" = module.travel-database-secret.env_vars.SECRET}, "env_vars" = merge({"travel_database_postgresql_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.travel-database-postgresql.instance_connection_name, "travel_database_postgresql_CLOUD_SQL_DATABASE_HOST" = module.travel-database-postgresql.instance_first_ip_address, "travel_database_postgresql_CLOUD_SQL_DATABASE_NAME" = module.travel-database-postgresql.env_vars.CLOUD_SQL_DATABASE_NAME}, {"travel_data_mcp_server_SERVICE_ENDPOINT" = module.travel-data-mcp-server.service_uri}, {"travel_data_syncer_api_SERVICE_ENDPOINT" = module.travel-data-syncer-api.service_uri}, {"REDIS_CACHE_IP" = module.travel-redis-cache.host}), "ports" = {"container_port" = 8080}, "volume_mounts" = [{"mount_path" = "/cloudsql", "name" = "cloudsql"}]}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"], ["roles/run.invoker"], ["roles/run.invoker"], ["roles/aiplatform.user"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.travel-database-postgresql.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    travel_vertex_ai_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
}

module "travel-database-postgresql" {
  source                      = "github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql?ref=v26.2.2"
  project_id                  = "n26-learn-c2c-app-dev-1"
  name                        = "vector-db"
  edition                     = "ENTERPRISE_PLUS"
  database_version            = "POSTGRES_18"
  availability_type           = "REGIONAL"
  deletion_protection         = false
  database_flags              = [{"name" = "cloudsql.iam_authentication", "value" = "on"}]
  data_cache_enabled          = true
  tier                        = "db-perf-optimized-N-8"
  deletion_protection_enabled = false
  disk_autoresize             = true
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }
  iam_users = concat([{"email" = module.travel-backend-service.service_account_id.email, "id" = module.travel-backend-service.service_account_id.id, "type" = "CLOUD_IAM_SERVICE_ACCOUNT"}], [{"email" = module.travel-data-mcp-server.service_account_id.email, "id" = module.travel-data-mcp-server.service_account_id.id, "type" = "CLOUD_IAM_SERVICE_ACCOUNT"}], [{"id" = module.travel-data-syncer-api.service_account_id.id, "type" = "CLOUD_IAM_SERVICE_ACCOUNT", "email" = module.travel-data-syncer-api.service_account_id.email}])
}

module "travel-database-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "n26-learn-c2c-app-dev-1"
  name        = "db-credentials"
  secret_data = module.travel-database-postgresql.generated_user_password
}

module "travel-data-mcp-server" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.25.0"
  project_id                    = "n26-learn-c2c-app-dev-1"
  location                      = "us-central1"
  service_name                  = "data-mcp-server"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"travel_database_secret_SECRET" = module.travel-database-secret.env_vars.SECRET}, "env_vars" = {"travel_database_postgresql_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.travel-database-postgresql.instance_connection_name, "travel_database_postgresql_CLOUD_SQL_DATABASE_HOST" = module.travel-database-postgresql.instance_first_ip_address, "travel_database_postgresql_CLOUD_SQL_DATABASE_NAME" = module.travel-database-postgresql.env_vars.CLOUD_SQL_DATABASE_NAME}, "ports" = {"container_port" = 8080}, "volume_mounts" = [{"mount_path" = "/cloudsql", "name" = "cloudsql"}]}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"], ["roles/aiplatform.user"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.travel-database-postgresql.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    travel_vertex_ai_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
}

module "travel-data-syncer-api" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.25.0"
  project_id                    = "n26-learn-c2c-app-dev-1"
  location                      = "us-central1"
  service_name                  = "data-syncer-api"
  containers                    = [{"env_secret_vars" = {"travel_database_secret_SECRET" = module.travel-database-secret.env_vars.SECRET}, "env_vars" = {"travel_database_postgresql_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.travel-database-postgresql.instance_connection_name, "travel_database_postgresql_CLOUD_SQL_DATABASE_HOST" = module.travel-database-postgresql.instance_first_ip_address, "travel_database_postgresql_CLOUD_SQL_DATABASE_NAME" = module.travel-database-postgresql.env_vars.CLOUD_SQL_DATABASE_NAME}, "ports" = {"container_port" = 8080}, "volume_mounts" = [{"mount_path" = "/cloudsql", "name" = "cloudsql"}], "container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"], ["roles/aiplatform.user"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.travel-database-postgresql.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    travel_vertex_ai_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
}

module "travel-vertex-ai" {
  source        = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id    = "n26-learn-c2c-app-dev-1"
  activate_apis = ["aiplatform.googleapis.com"]
}

module "travel-redis-cache" {
  source  = "terraform-google-modules/memorystore/google"
  version = "~> 7.0"
  
  name                    = "gemini-query-cache"
  project                 = "n26-learn-c2c-app-dev-1"
  region                  = "us-central1"
  tier                    = "BASIC"
  memory_size_gb          = 1
  authorized_network      = "default"
}
