# outputs.tf

# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "travel-global-lb-frontend_external_ip" {
  description = "The external IPv4 assigned to the global fowarding rule."
  value       = module.travel-global-lb-frontend.external_ip
}
output "travel-global-lb-frontend_external_ipv6_address" {
  description = "The external IPv6 assigned to the global fowarding rule."
  value       = module.travel-global-lb-frontend.external_ipv6_address
}
output "travel-global-lb-frontend_ip_address_internal_managed_http" {
  description = "The internal/external IP addresses assigned to the HTTP forwarding rules."
  value       = module.travel-global-lb-frontend.ip_address_internal_managed_http
}
output "travel-global-lb-frontend_ip_address_internal_managed_https" {
  description = "The internal/external IP addresses assigned to the HTTPS forwarding rules."
  value       = module.travel-global-lb-frontend.ip_address_internal_managed_https
}
output "travel-frontend-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.travel-frontend-service.service_uri
}
output "travel-backend-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.travel-backend-service.service_uri
}
output "travel-data-mcp-server_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.travel-data-mcp-server.service_uri
}
output "travel-data-syncer-api_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.travel-data-syncer-api.service_uri
}
output "travel-redis-cache_host" {
  description = "The IP address of the Memorystore Redis cache."
  value       = module.travel-redis-cache.host
}
