# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/n26-learn-c2c-app-dev-6/locations/us-central1/spaces/default-space/applicationTemplates/london-travel-agent-template

module "global-lb-frontend" {
  source        = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v14.2.0"
  name          = "global-lb-frontend"
  project_id    = "n26-learn-c2c-app-dev-6"
  url_map_input = module.global-lb-backend.backend_service_info
}
module "global-lb-backend" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v14.2.0"
  name       = "global-lb-backend"
  project_id = "n26-learn-c2c-app-dev-6"
  serverless_neg_backends = [{
    region          = module.frontend.location
    service_name    = module.frontend.service_name
    service_version = ""
    type            = "cloud-run"
  }]
}
module "frontend" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.25.2"
  project_id                    = "n26-learn-c2c-app-dev-6"
  location                      = "us-central1"
  service_name                  = "frontend"
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/o11y-movie-guru/london-travel-agency/frontend:codelab-c2c6-v1", "env_vars" = merge({"agent_SERVICE_ENDPOINT" = module.agent.service_uri}, {"API_BASE_URL" = module.agent.service_uri})}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/run.invoker"]
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "agent" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.25.2"
  project_id                    = "n26-learn-c2c-app-dev-6"
  location                      = "us-central1"
  service_name                  = "agent"
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/o11y-movie-guru/london-travel-agency/agent:codelab-c2c6-v1", "env_vars" = merge({"london_data_mcp_SERVICE_ENDPOINT" = module.london-data-mcp.service_uri}, {"DATA_BACKEND_URL" = module.london_data_mcp.service_uri, "GOOGLE_CLOUD_LOCATION" = "us-central1", "GOOGLE_CLOUD_PROJECT" = "n26-learn-c2c-app-dev-6"})}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/run.invoker"], ["roles/aiplatform.user"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    vertex_ai_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "london-data-mcp" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.25.2"
  project_id                    = "n26-learn-c2c-app-dev-6"
  location                      = "us-central1"
  service_name                  = "london-data-mcp"
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/o11y-movie-guru/london-travel-agency/data_mcp:codelab-c2c6-v1", "env_secret_vars" = {"secret_manager_SECRET" = module.secret-manager.env_vars.SECRET}, "env_vars" = merge({"database_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.database.instance_connection_name, "database_CLOUD_SQL_DATABASE_HOST" = module.database.instance_first_ip_address, "database_CLOUD_SQL_DATABASE_NAME" = module.database.env_vars.CLOUD_SQL_DATABASE_NAME}, {"POSTGRES_HOST" = module.database.private_ip_address, "POSTGRES_PASSWORD" = module.database.user_password, "POSTGRES_PORT" = "5432", "POSTGRES_USER" = module.database.user_name, "DB_TYPE" = "postgres", "GOOGLE_CLOUD_LOCATION" = "us-central1", "GOOGLE_CLOUD_PROJECT" = "n26-learn-c2c-app-dev-6", "POSTGRES_DB" = "london_travel"}), "volume_mounts" = [{"mount_path" = "/cloudsql", "name" = "cloudsql"}]}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.database.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "data-syncer" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.25.2"
  project_id                    = "n26-learn-c2c-app-dev-6"
  location                      = "us-central1"
  service_name                  = "data-syncer"
  containers                    = [{"env_secret_vars" = {"secret_manager_syncer_SECRET" = module.secret-manager-syncer.env_vars.SECRET}, "env_vars" = merge({"database_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.database.instance_connection_name, "database_CLOUD_SQL_DATABASE_HOST" = module.database.instance_first_ip_address, "database_CLOUD_SQL_DATABASE_NAME" = module.database.env_vars.CLOUD_SQL_DATABASE_NAME}, {"POSTGRES_PASSWORD" = module.database.user_password, "POSTGRES_PORT" = "5432", "POSTGRES_USER" = module.database.user_name, "GOOGLE_CLOUD_LOCATION" = "us-central1", "GOOGLE_CLOUD_PROJECT" = "n26-learn-c2c-app-dev-6", "POSTGRES_DB" = "london_travel", "POSTGRES_HOST" = module.database.private_ip_address}), "volume_mounts" = [{"mount_path" = "/cloudsql", "name" = "cloudsql"}], "container_image" = "us-central1-docker.pkg.dev/o11y-movie-guru/london-travel-agency/data_syncer:codelab-c2c6-v1"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes                       = [{"cloud_sql_instance" = {"instances" = [module.database.instance_connection_name]}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "database" {
  source                      = "github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql?ref=v26.2.2"
  project_id                  = "n26-learn-c2c-app-dev-6"
  name                        = "database"
  edition                     = "ENTERPRISE_PLUS"
  database_version            = "POSTGRES_15"
  availability_type           = "REGIONAL"
  deletion_protection         = false
  database_flags              = [{"name" = "google_columnar_engine.enabled", "value" = "on"}]
  data_cache_enabled          = true
  tier                        = "db-perf-optimized-N-8"
  deletion_protection_enabled = false
  disk_autoresize             = true
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }
  iam_users = concat([{"email" = module.london-data-mcp.service_account_id.email, "id" = module.london-data-mcp.service_account_id.id, "type" = "CLOUD_IAM_SERVICE_ACCOUNT"}], [{"id" = module.data-syncer.service_account_id.id, "type" = "CLOUD_IAM_SERVICE_ACCOUNT", "email" = module.data-syncer.service_account_id.email}])
}
module "secret-manager" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "n26-learn-c2c-app-dev-6"
  name        = "db-credentials"
  secret_data = module.database.generated_user_password
}
module "vertex-ai" {
  source        = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id    = "n26-learn-c2c-app-dev-6"
  activate_apis = ["aiplatform.googleapis.com"]
}
module "secret-manager-syncer" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "n26-learn-c2c-app-dev-6"
  name        = "db-credentials-syncer"
  secret_data = module.database.generated_user_password
}
