
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/n26-learn-c2c-app-dev-6/locations/us-central1/spaces/default-space/applicationTemplates/london-travel-agent-template

module "global-lb-backend" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v14.2.0"
  name       = var.global-lb-backend_name
  project_id = var.global-lb-backend_project_id
  serverless_neg_backends = [{
    region          = module.frontend.location
    service_name    = module.frontend.service_name
    service_version = ""
    type            = "cloud-run"
  }]
  cdn_policy = {
    cache_mode                   = "CACHE_ALL_STATIC"
    client_ttl                   = 3600
    default_ttl                  = 3600
    max_ttl                      = 86400
    signed_url_cache_max_age_sec = "0"
  }
  depends_on = [module.project-services-n26-learn-c2c-app-dev-6, module.project-services-billing-project]
}
module "data-syncer" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.25.2"
  project_id                    = var.data-syncer_project_id
  location                      = var.data-syncer_location
  service_name                  = var.data-syncer_service_name
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/o11y-movie-guru/london-travel-agency/data_syncer:v4", "container_name" = "server", "env_secret_vars" = {"POSTGRES_PASSWORD" = module.db-credentials-secret.env_vars.SECRET}, "env_vars" = merge({"POSTGRES_DB" = module.postgresql-db.env_vars.CLOUD_SQL_DATABASE_NAME, "POSTGRES_HOST" = module.postgresql-db.instance_first_ip_address, "postgresql-db_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.postgresql-db.instance_connection_name}, {"POSTGRES_HOST" = module.postgresql-db.public_ip_address, "POSTGRES_USER" = "londondatauser", "EMBEDDING_MODEL" = "text-embedding-005", "GOOGLE_CLOUD_LOCATION" = "us-central1", "GOOGLE_CLOUD_PROJECT" = "n26-learn-c2c-app-dev-6", "POSTGRES_DB" = "london_travel"}), "ports" = {"container_port" = 8001, "name" = "http1"}, "resources" = {"cpu_idle" = true, "startup_cpu_boost" = false}, "volume_mounts" = concat([{"mount_path" = "/cloudsql", "name" = "cloudsql"}], [{"mount_path" = "/cloudsql", "name" = "cloudsql"}])}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/aiplatform.user"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/cloudsql.client", "roles/logging.logWriter", "roles/cloudtrace.agent", "roles/monitoring.metricWriter", "roles/telemetry.writer"])
  members                       = ["allUsers"]
  vpc_access = {
    egress = "PRIVATE_RANGES_ONLY"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = false
  volumes                       = [{"cloud_sql_instance" = {"instances" = concat([module.postgresql-db.instance_connection_name], [module.postgresql-db.instance_connection_name])}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    vertex_ai_1_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-n26-learn-c2c-app-dev-6, module.project-services-billing-project]
}
module "lb-frontend-1" {
  source        = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v14.2.0"
  name          = var.lb-frontend-1_name
  project_id    = var.lb-frontend-1_project_id
  url_map_input = module.global-lb-backend.backend_service_info
  depends_on    = [module.project-services-n26-learn-c2c-app-dev-6, module.project-services-billing-project]
}
module "db-credentials-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = var.db-credentials-secret_project_id
  name        = var.db-credentials-secret_name
  secret_data = module.postgresql-db.generated_user_password
  depends_on  = [module.project-services-n26-learn-c2c-app-dev-6, module.project-services-billing-project]
}
module "frontend" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.25.0"
  project_id                    = var.frontend_project_id
  location                      = var.frontend_location
  service_name                  = var.frontend_service_name
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/o11y-movie-guru/london-travel-agency/frontend:v4", "container_name" = "service-container", "env_vars" = {"API_BASE_URL" = module.agent.service_uri}, "ports" = {"container_port" = 80, "name" = "http1"}, "resources" = {"cpu_idle" = true, "startup_cpu_boost" = false}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/run.invoker"]
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  members                       = ["allUsers"]
  vpc_access = {
    egress = "PRIVATE_RANGES_ONLY"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-n26-learn-c2c-app-dev-6, module.project-services-billing-project]
}
module "london-data-mcp" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.25.0"
  project_id                    = var.london-data-mcp_project_id
  location                      = var.london-data-mcp_location
  service_name                  = var.london-data-mcp_service_name
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/o11y-movie-guru/london-travel-agency/data_mcp:v4", "container_name" = "server", "env_secret_vars" = {"POSTGRES_PASSWORD" = module.db-credentials-secret.env_vars.SECRET}, "env_vars" = merge({"POSTGRES_DB" = module.postgresql-db.env_vars.CLOUD_SQL_DATABASE_NAME, "POSTGRES_HOST" = module.postgresql-db.instance_first_ip_address, "postgresql_db_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.postgresql-db.instance_connection_name}, {"POSTGRES_HOST" = module.postgresql-db.public_ip_address, "POSTGRES_USER" = "londondatauser", "DB_TYPE" = "postgres", "EMBEDDING_MODEL" = "text-embedding-005", "GOOGLE_CLOUD_LOCATION" = "us-central1", "GOOGLE_CLOUD_PROJECT" = "n26-learn-c2c-app-dev-6", "POSTGRES_DB" = "london_travel"}), "ports" = {"name" = "http1", "container_port" = 8002}, "resources" = {"cpu_idle" = true, "startup_cpu_boost" = false}, "volume_mounts" = concat([{"mount_path" = "/cloudsql", "name" = "cloudsql"}], [{"mount_path" = "/cloudsql", "name" = "cloudsql"}])}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/aiplatform.user"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/cloudsql.client", "roles/monitoring.metricWriter", "roles/cloudtrace.agent", "roles/logging.logWriter", "roles/telemetry.writer"])
  vpc_access = {
    egress = "PRIVATE_RANGES_ONLY"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = false
  volumes                       = [{"cloud_sql_instance" = {"instances" = concat([module.postgresql-db.instance_connection_name], [module.postgresql-db.instance_connection_name])}, "name" = "cloudsql"}]
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    vertex_ai_1_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-n26-learn-c2c-app-dev-6, module.project-services-billing-project]
}
module "vertex-ai" {
  source        = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id    = var.vertex-ai_project_id
  activate_apis = ["aiplatform.googleapis.com"]
  depends_on    = [module.project-services-n26-learn-c2c-app-dev-6, module.project-services-billing-project]
}
module "agent" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.25.0"
  project_id                    = var.agent_project_id
  location                      = var.agent_location
  service_name                  = var.agent_service_name
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/o11y-movie-guru/london-travel-agency/agent:v4", "container_name" = "service", "env_vars" = merge({"DATA_BACKEND_URL" = module.london-data-mcp.service_uri}, {"GOOGLE_CLOUD_LOCATION" = "us-central1", "GOOGLE_CLOUD_PROJECT" = "n26-learn-c2c-app-dev-6", "GOOGLE_GENAI_USE_VERTEXAI" = "true", "OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT" = "true", "OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED" = "true"}), "ports" = {"container_port" = 8000, "name" = "http1"}, "resources" = {"cpu_idle" = true, "startup_cpu_boost" = false}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/run.invoker"], ["roles/aiplatform.user"], ["roles/monitoring.metricWriter", "roles/aiplatform.user", "roles/cloudtrace.agent", "roles/logging.logWriter", "roles/telemetry.writer", "roles/serviceusage.serviceUsageConsumer", "roles/bigquery.jobUser", "roles/bigquery.dataEditor", "roles/modelarmor.user"])
  members                       = ["allUsers"]
  vpc_access = {
    egress = "PRIVATE_RANGES_ONLY"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = false
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    vertex_ai_1_vertex-ai = "true"
  }
  template_scaling = {
    max_instance_count = 5
    min_instance_count = 1
  }
  depends_on = [module.project-services-n26-learn-c2c-app-dev-6, module.project-services-billing-project]
}
module "postgresql-db" {
  source                      = "github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql?ref=v26.2.2"
  project_id                  = var.postgresql-db_project_id
  region                      = var.postgresql-db_region
  name                        = var.postgresql-db_name
  edition                     = "ENTERPRISE"
  database_version            = var.postgresql-db_database_version
  availability_type           = "REGIONAL"
  db_name                     = "london_travel"
  user_name                   = "londondatauser"
  deletion_protection         = false
  database_flags              = [{"name" = "cloudsql.iam_authentication", "value" = "on"}]
  data_cache_enabled          = false
  tier                        = "db-g1-small"
  deletion_protection_enabled = false
  disk_autoresize             = true
  backup_configuration = {
    enabled                        = false
    point_in_time_recovery_enabled = false
  }
  ip_configuration = {
    authorized_networks = [{
      key   = "default"
      value = "0.0.0.0/0"
    }]
    enable_private_path_for_google_cloud_services = false
    ipv4_enabled                                  = true
    psc_enabled                                   = false
  }
  iam_users  = concat([{"email" = module.data-syncer.service_account_id.email, "id" = module.data-syncer.service_account_id.id, "type" = "CLOUD_IAM_SERVICE_ACCOUNT"}], [{"id" = module.london-data-mcp.service_account_id.id, "type" = "CLOUD_IAM_SERVICE_ACCOUNT", "email" = module.london-data-mcp.service_account_id.email}])
  depends_on = [module.project-services-n26-learn-c2c-app-dev-6, module.project-services-billing-project]
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = concat(module.global-lb-backend.apphub_service_uri, [module.data-syncer.apphub_service_uri], module.lb-frontend-1.apphub_service_uri, [module.frontend.apphub_service_uri], [module.london-data-mcp.apphub_service_uri], [module.agent.apphub_service_uri], [module.postgresql-db.apphub_service_uri])
  application_id = var.apphub_application_id
}
module "project-services-n26-learn-c2c-app-dev-6" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "n26-learn-c2c-app-dev-6"
  disable_services_on_destroy = false
  activate_apis               = ["accesscontextmanager.googleapis.com", "admin.googleapis.com", "appengine.googleapis.com", "billingbudgets.googleapis.com", "certificatemanager.googleapis.com", "cloudbilling.googleapis.com", "cloudkms.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "essentialcontacts.googleapis.com", "iam.googleapis.com", "iamcredentials.googleapis.com", "iap.googleapis.com", "monitoring.googleapis.com", "oslogin.googleapis.com", "pubsub.googleapis.com", "run.googleapis.com", "secretmanager.googleapis.com", "serviceconsumermanagement.googleapis.com", "servicenetworking.googleapis.com", "serviceusage.googleapis.com", "sqladmin.googleapis.com", "storage-api.googleapis.com", "vpcaccess.googleapis.com"]
}
module "project-services-billing-project" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "n26-learn-c2c-app-dev-6"
  disable_services_on_destroy = false
  activate_apis               = ["accesscontextmanager.googleapis.com", "admin.googleapis.com", "appengine.googleapis.com", "apphub.googleapis.com", "billingbudgets.googleapis.com", "certificatemanager.googleapis.com", "cloudbilling.googleapis.com", "cloudkms.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "essentialcontacts.googleapis.com", "iam.googleapis.com", "iamcredentials.googleapis.com", "iap.googleapis.com", "monitoring.googleapis.com", "oslogin.googleapis.com", "pubsub.googleapis.com", "run.googleapis.com", "secretmanager.googleapis.com", "serviceconsumermanagement.googleapis.com", "servicenetworking.googleapis.com", "serviceusage.googleapis.com", "sqladmin.googleapis.com", "storage-api.googleapis.com", "vpcaccess.googleapis.com"]
}
