
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/n26-learn-c2c-app-dev-6/locations/us-central1/spaces/default-space/applicationTemplates/london-travel-agent-template

output "data-syncer_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.data-syncer.service_uri
}
output "lb-frontend-1_external_ip" {
  description = "The external IPv4 assigned to the global fowarding rule."
  value       = module.lb-frontend-1.external_ip
}
output "lb-frontend-1_external_ipv6_address" {
  description = "The external IPv6 assigned to the global fowarding rule."
  value       = module.lb-frontend-1.external_ipv6_address
}
output "lb-frontend-1_ip_address_internal_managed_http" {
  description = "The internal/external IP addresses assigned to the HTTP forwarding rules."
  value       = module.lb-frontend-1.ip_address_internal_managed_http
}
output "lb-frontend-1_ip_address_internal_managed_https" {
  description = "The internal/external IP addresses assigned to the HTTPS forwarding rules."
  value       = module.lb-frontend-1.ip_address_internal_managed_https
}
output "frontend_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.frontend.service_uri
}
output "london-data-mcp_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.london-data-mcp.service_uri
}
output "agent_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.agent.service_uri
}
