# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/n26-learn-c2c-app-dev-6/locations/us-central1/spaces/default-space/applicationTemplates/london-travel-agent-template

provider "google" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
}
provider "google-beta" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
}
