# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/n26-learn-c2c-app-dev-6/locations/us-central1/spaces/default-space/applicationTemplates/london-travel-agent-template

variable "global-lb-backend_name" {
  description = "Name for the backend service."
  type = string
}
variable "global-lb-backend_project_id" {
  description = "The project to deploy to, if not set the default provider project is used."
  type = string
}
variable "data-syncer_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "data-syncer_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "data-syncer_service_name" {
  description = "The name of the Cloud Run service to create"
  type = string
}
variable "lb-frontend-1_name" {
  description = "Name for the forwarding rule and prefix for supporting resources"
  type = string
}
variable "lb-frontend-1_project_id" {
  description = "The project to deploy to, if not set the default provider project is used."
  type = string
}
variable "db-credentials-secret_project_id" {
  description = "The project ID to manage the Secret Manager resources"
  type = string
}
variable "db-credentials-secret_name" {
  description = "The name of the secret to create."
  type = string
}
variable "frontend_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "frontend_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "frontend_service_name" {
  description = "The name of the Cloud Run service to create"
  type = string
}
variable "london-data-mcp_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "london-data-mcp_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "london-data-mcp_service_name" {
  description = "The name of the Cloud Run service to create"
  type = string
}
variable "vertex-ai_project_id" {
  description = "The GCP project you want to enable APIs on"
  type = string
}
variable "agent_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "agent_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "agent_service_name" {
  description = "The name of the Cloud Run service to create"
  type = string
}
variable "postgresql-db_project_id" {
  description = "The project ID to manage the Cloud SQL resources"
  type = string
}
variable "postgresql-db_region" {
  description = "The region of the Cloud SQL resources"
  default     = "us-central1"
  type = string
}
variable "postgresql-db_name" {
  description = "The name of the Cloud SQL instance"
  type = string
}
variable "postgresql-db_database_version" {
  description = "The database version to use. Can be 9_6, 14, 15, 16, 17."
  type = string
}
variable "apphub_project_id" {
  description = "The project ID of the host project where AppHub application is created."
  type = string
}
variable "apphub_location" {
  description = "The location of AppHub application."
  type = string
}
variable "apphub_application_id" {
  description = "The AppHub application identifier"
  type = string
}
