
BEGIN TRANSACTION;
CREATE TABLE "activities" (
"activity_id" TEXT,
  "name" TEXT,
  "kid_friendliness_score" INTEGER,
  "cost_gbp" REAL,
  "description" TEXT,
  "sight_id" TEXT,
  "duration_min" INTEGER,
  "duration_max" INTEGER
);
INSERT INTO "activities" VALUES('LON-001-A1','General Highlights Exploration',4,0.0,'Wander through the vast collection at your own pace, ensuring you see iconic artifacts like the Rosetta Stone, the Parthenon Marbles, and the Egyptian mummies.','LON-001',120,240);
INSERT INTO "activities" VALUES('LON-001-A2','Expert-Led ''Around the World in 90 Minutes'' Tour',3,15.0,'Join an official museum guide for a fast-paced tour of the museum''s most famous and significant artifacts from across the globe.','LON-001',90,90);
INSERT INTO "activities" VALUES('LON-001-A3','Family Fun: Museum Mission',5,0.0,'Pick up a free family trail from the information desk and turn your visit into an exciting treasure hunt through history.','LON-001',60,90);
INSERT INTO "activities" VALUES('LON-002-A1','Full Tower Exploration & Crown Jewels',4,34.0,'Explore the entire historic fortress, see the magnificent Crown Jewels, walk the ancient walls, and visit the White Tower.','LON-002',180,240);
INSERT INTO "activities" VALUES('LON-002-A2','Yeoman Warder ''Beefeater'' Tour',5,0.0,'Be entertained by the captivating and often gruesome tales of the Tower''s history on this highly engaging guided tour. Included with admission.','LON-002',60,60);
INSERT INTO "activities" VALUES('LON-002-A3','Ceremony of the Keys',2,5.0,'Witness the ancient nightly gate-locking ritual. This is a ticketed event that must be booked months in advance.','LON-002',35,35);
INSERT INTO "activities" VALUES('LON-003-A1','Standard London Eye Rotation',5,30.0,'Take a 30-minute rotation in one of the iconic glass pods for stunning 360-degree views of London. Total experience time is longer.','LON-003',30,45);
INSERT INTO "activities" VALUES('LON-003-A2','London Eye: Fast Track',5,45.0,'Beat the queues with a pre-booked fast track ticket, giving you more time to enjoy the rest of the city.','LON-003',30,45);
INSERT INTO "activities" VALUES('LON-004-A1','Witness the Changing of the Guard',4,0.0,'Experience the world-famous display of British pageantry outside the palace gates. Arrive at least 30-45 minutes early for a good view. (Exterior only)','LON-004',45,60);
INSERT INTO "activities" VALUES('LON-004-A2','Summer Opening: State Rooms Tour',2,35.0,'Gain rare access to the lavishly furnished State Rooms used by The King for official events. (Available for a limited period in summer)','LON-004',120,150);
INSERT INTO "activities" VALUES('LON-004-A3','Palace Exterior Photo Opportunity',5,0.0,'Take iconic photos in front of the famous palace gates and the Victoria Memorial.','LON-004',15,20);
INSERT INTO "activities" VALUES('LON-005-A1','Leisurely Park Stroll & Picnic',5,0.0,'Enjoy a walk or picnic, visit the Serpentine Lake and Princess Diana Memorial Fountain, and relax in this vast green oasis.','LON-005',60,180);
INSERT INTO "activities" VALUES('LON-005-A2','Boating on the Serpentine Lake',5,12.0,'Rent a paddle boat or rowing boat for a fun and relaxing time on the famous lake. (Seasonal)','LON-005',30,60);
INSERT INTO "activities" VALUES('LON-005-A3','Visit Speaker''s Corner',2,0.0,'Witness the home of free speech, where people from all walks of life share their views on a Sunday morning.','LON-005',20,40);
INSERT INTO "activities" VALUES('LON-006-A1','Westminster Abbey Entry with Audio Guide',3,27.0,'Explore this stunning Gothic church, the site of royal coronations, weddings, and the resting place of many historical figures.','LON-006',90,120);
INSERT INTO "activities" VALUES('LON-006-A2','Attend Evensong Service',3,0.0,'Experience the Abbey''s magnificent acoustics by attending a beautiful, traditional choral Evensong service. (Donations welcome)','LON-006',45,60);
INSERT INTO "activities" VALUES('LON-007-A1','Photo Stop at Big Ben & Parliament',5,0.0,'Admire and photograph the iconic exterior of the Houses of Parliament and the Elizabeth Tower (Big Ben) from Parliament Square or across the river.','LON-007',15,30);
INSERT INTO "activities" VALUES('LON-007-A2','Guided Tour of the Houses of Parliament',3,29.0,'Discover the heart of UK politics with a tour through the House of Commons, House of Lords, and historic Westminster Hall. (Booking essential)','LON-007',90,90);
INSERT INTO "activities" VALUES('LON-008-A1','Explore Tate Modern''s Free Collection',4,0.0,'Discover international modern and contemporary art, from Picasso to Warhol, in the spectacular Turbine Hall and gallery spaces.','LON-008',120,180);
INSERT INTO "activities" VALUES('LON-008-A2','View from the Blavatnik Building',4,0.0,'Take the lift to the viewing level of the Blavatnik Building for a fantastic free panoramic view of the London skyline.','LON-008',20,30);
INSERT INTO "activities" VALUES('LON-009-A1','Cathedral Entry, Dome Climb & Crypt',3,25.0,'Explore Wren''s masterpiece, whisper in the Whispering Gallery, climb to the Golden Gallery for spectacular views, and visit the crypt.','LON-009',90,150);
INSERT INTO "activities" VALUES('LON-009-A2','Experience a Choral Service',3,0.0,'Listen to the world-renowned choir during a service for a truly moving and atmospheric experience. (Donations welcome)','LON-009',50,60);
INSERT INTO "activities" VALUES('LON-010-A1','Dinosaur & Earth Hall Encounter',5,0.0,'Marvel at the giant dinosaur skeletons, feel the earth shake in the earthquake simulator, and explore the vast collection of natural wonders.','LON-010',150,240);
INSERT INTO "activities" VALUES('LON-010-A2','Visit a Ticketed Exhibition',4,16.0,'Explore one of the museum''s world-class temporary exhibitions, often focusing on wildlife photography or specific scientific topics.','LON-010',60,90);
INSERT INTO "activities" VALUES('LON-011-A1','V&A General Visit',4,0.0,'Explore the world''s leading museum of art and design, with treasures from fashion and jewellery to furniture and sculpture.','LON-011',120,240);
INSERT INTO "activities" VALUES('LON-011-A2','Focus on Fashion and Jewellery',3,0.0,'Dedicate your time to the V&A''s world-renowned fashion collection and the stunning William and Judith Bollinger Jewellery Gallery.','LON-011',60,90);
INSERT INTO "activities" VALUES('LON-012-A1','General Science Exploration',5,0.0,'Discover world-changing inventions, from Stephenson''s Rocket to the Apollo 10 command module, across multiple floors of exhibits.','LON-012',120,180);
INSERT INTO "activities" VALUES('LON-012-A2','Wonderlab: The Equinor Gallery',5,12.0,'Get hands-on with real scientific phenomena through interactive exhibits, shows, and demonstrations. (Ticketed)','LON-012',90,120);
INSERT INTO "activities" VALUES('LON-013-A1','Masterpieces of Western Art',3,0.0,'See world-famous works by Van Gogh (Sunflowers), da Vinci, Botticelli, Turner, and many others in this world-class art gallery.','LON-013',90,150);
INSERT INTO "activities" VALUES('LON-013-A2','Free ''Art in the Making'' Tour',3,0.0,'Join a free daily talk to learn more about the techniques and stories behind some of the collection''s greatest paintings.','LON-013',60,60);
INSERT INTO "activities" VALUES('LON-014-A1','Tower Bridge Exhibition',4,12.3,'Walk across the high-level glass walkway, see the Victorian Engine Rooms, and learn about the bridge''s history and engineering.','LON-014',60,90);
INSERT INTO "activities" VALUES('LON-014-A2','Watch a Bridge Lift',5,0.0,'Check the lift times online and watch the iconic bascules raise to allow a tall ship to pass through. A fantastic free spectacle.','LON-014',15,20);
INSERT INTO "activities" VALUES('LON-015-A1','Watch a Play as a ''Groundling''',3,5.0,'Experience a play as an Elizabethan would have, standing in the open-air yard for an authentic and immersive theatrical experience.','LON-015',150,210);
INSERT INTO "activities" VALUES('LON-015-A2','Shakespeare''s Globe Theatre Tour',4,17.0,'Take an expertly guided tour of this faithful reconstruction of Shakespeare''s iconic ''wooden O'' theatre. (Separate from play tickets)','LON-015',50,50);
INSERT INTO "activities" VALUES('LON-016-A1','The View from The Shard',4,32.0,'Ascend to the top of Western Europe''s tallest building for breathtaking 360-degree views from the indoor and open-air viewing platforms.','LON-016',60,90);
INSERT INTO "activities" VALUES('LON-016-A2','Cocktails at Aqua Shard',1,20.0,'Enjoy a sophisticated cocktail with stunning views from the atrium bar on level 31. (Cost is for one cocktail)','LON-016',60,90);
INSERT INTO "activities" VALUES('LON-017-A1','Gourmet Street Food Lunch',4,15.0,'Explore the vibrant stalls and choose from a huge variety of delicious street food options for lunch.','LON-017',60,90);
INSERT INTO "activities" VALUES('LON-017-A2','Artisan Produce Shopping',3,25.0,'Browse and buy from a huge range of high-quality produce, including artisan cheeses, cured meats, fresh bread, and olives.','LON-017',45,60);
INSERT INTO "activities" VALUES('LON-018-A1','Watch Street Performers in the Piazza',5,0.0,'Find a spot on the steps and enjoy the free, high-quality street entertainment, from opera singers to magicians.','LON-018',30,60);
INSERT INTO "activities" VALUES('LON-018-A2','Explore the Apple Market',4,10.0,'Browse the stalls in the covered market for unique handmade crafts, jewellery, and antiques. (Cost is an estimate for a small purchase)','LON-018',45,75);
INSERT INTO "activities" VALUES('LON-019-A1','Kensington Palace Admission',3,25.0,'Explore the birthplace of Queen Victoria and home to young royals for centuries. See the King''s and Queen''s State Apartments.','LON-019',120,180);
INSERT INTO "activities" VALUES('LON-019-A2','Walk through the Palace Gardens',5,0.0,'Enjoy a stroll through the beautiful and serene formal gardens adjacent to the palace, a peaceful escape from the city.','LON-019',30,45);
INSERT INTO "activities" VALUES('LON-020-A1','Stroll Queen Mary''s Gardens',5,0.0,'Visit one of London''s most beautiful formal gardens, especially in early summer when the 12,000 roses are in bloom.','LON-020',45,60);
INSERT INTO "activities" VALUES('LON-020-A2','Pedalo Boating on Regent''s Park Lake',5,10.0,'Hire a pedalo and enjoy a fun trip around the picturesque boating lake. (Seasonal)','LON-020',30,60);
INSERT INTO "activities" VALUES('LON-020-A3','Visit the Open Air Theatre',3,40.0,'Catch a play or musical in a magical setting during the summer season. A unique London experience.','LON-020',120,180);
INSERT INTO "activities" VALUES('LON-021-A1','Explore Camden Market',3,20.0,'Get lost in the labyrinth of stalls selling alternative fashion, unique gifts, and crafts. (Cost is estimate for purchase)','LON-021',120,240);
INSERT INTO "activities" VALUES('LON-021-A2','Global Street Food Feast',4,12.0,'Sample delicious food from around the world from the extensive street food section by the canal.','LON-021',45,75);
INSERT INTO "activities" VALUES('LON-022-A1','Walk to the General Wolfe Statue Viewpoint',5,0.0,'Hike to the top of the hill for one of London''s most iconic and protected views, overlooking the Queen''s House and the skyscrapers of Canary Wharf.','LON-022',45,90);
INSERT INTO "activities" VALUES('LON-022-A2','Relax by the Flower Garden and Pond',5,0.0,'Find the tranquil enclosed garden area for a peaceful rest among beautiful flowerbeds and a duck pond.','LON-022',30,60);
INSERT INTO "activities" VALUES('LON-023-A1','Stand on the Prime Meridian Line',5,16.0,'Visit the home of Greenwich Mean Time (GMT), straddle the Prime Meridian with one foot in each hemisphere, and explore the historic observatory.','LON-023',60,120);
INSERT INTO "activities" VALUES('LON-023-A2','Attend a Planetarium Show',5,10.0,'Journey through space in a stunning show at the Peter Harrison Planetarium. (Can be booked with or without observatory entry)','LON-023',45,60);
INSERT INTO "activities" VALUES('LON-024-A1','Explore the Cutty Sark',4,16.0,'Climb aboard the world''s sole surviving tea clipper, walk beneath its gleaming copper hull, and discover life at sea.','LON-024',90,120);
INSERT INTO "activities" VALUES('LON-025-A1','Trafalgar Square Photo Stop',5,0.0,'Visit the famous square, take photos with Nelson''s Column and the iconic lion statues, and see the fountains.','LON-025',20,40);
INSERT INTO "activities" VALUES('LON-025-A2','See the Fourth Plinth Artwork',4,0.0,'Check out the latest contemporary art installation on the famous ''Fourth Plinth'' in the north-west corner of the square.','LON-025',10,15);
INSERT INTO "activities" VALUES('LON-026-A1','Experience the Piccadilly Lights',4,0.0,'Soak in the atmosphere of London''s ''Times Square'', with its huge video displays and the statue of Eros. Best experienced at dusk.','LON-026',15,30);
INSERT INTO "activities" VALUES('LON-027-A1','Churchill War Rooms & Museum Tour',3,27.0,'Explore the secret underground headquarters where Churchill directed WWII and learn about his life in the interactive museum.','LON-027',120,150);
INSERT INTO "activities" VALUES('LON-028-A1','Hampton Court Palace, Gardens & Maze',5,26.0,'Discover the magnificent Tudor palace of Henry VIII, explore the stunning gardens, and get lost in the world-famous maze.','LON-028',240,360);
INSERT INTO "activities" VALUES('LON-029-A1','Full Day at Kew Gardens',5,20.0,'Spend a day exploring the vast botanical gardens, iconic Victorian glasshouses (the Palm House and Temperate House), and treetop walkway.','LON-029',240,420);
INSERT INTO "activities" VALUES('LON-029-A2','Visit The Hive and Great Pagoda',4,20.0,'Focus your visit on the multi-sensory Hive installation and climb the newly restored Great Pagoda for fantastic views. (Included in entry)','LON-029',90,120);
INSERT INTO "activities" VALUES('LON-030-A1','ZSL London Zoo Adventure',5,33.0,'Spend a day discovering thousands of animals at the world''s oldest scientific zoo, seeing exhibits like Land of the Lions and Gorilla Kingdom.','LON-030',240,360);
INSERT INTO "activities" VALUES('LON-031-A1','Explore The National Portrait Gallery',3,0.0,'Discover portraits of famous and influential Britons from the Tudors to today, following a major refurbishment.','LON-031',90,150);
INSERT INTO "activities" VALUES('LON-032-A1','Imperial War Museum London Visit',3,0.0,'Explore powerful exhibits on modern conflict, from the immersive WWI galleries to the thought-provoking Holocaust exhibition.','LON-032',150,210);
INSERT INTO "activities" VALUES('LON-033-A1','Discover The Wallace Collection',3,0.0,'Step into a historic London townhouse and discover a treasure trove of fine art, furniture, and armour, including Hals'' ''The Laughing Cavalier''.','LON-033',90,120);
INSERT INTO "activities" VALUES('LON-034-A1','Explore Sir John Soane''s Museum',2,0.0,'Explore the eccentric and atmospheric house-museum, packed with art, antiquities, and curiosities. A truly unique experience.','LON-034',60,90);
INSERT INTO "activities" VALUES('LON-035-A1','Luxury Window Shopping',3,0.0,'Experience the opulence and stunning window displays of one of the world''s most famous department stores.','LON-035',60,90);
INSERT INTO "activities" VALUES('LON-035-A2','Explore the Food Halls',4,25.0,'Marvel at the spectacular displays in the ornate Food Halls and perhaps buy a luxury treat. (Cost is an estimate for purchase)','LON-035',45,75);
INSERT INTO "activities" VALUES('LON-036-A1','The Globe Theatre Tour & Exhibition',4,17.0,'An expertly guided tour exploring the story of the iconic Globe Theatre and the London of Shakespeare''s time.','LON-036',50,50);
INSERT INTO "activities" VALUES('LON-037-A1','Explore Tate Britain',3,0.0,'Walk through the home of British art from 1500 to the present day, with dedicated galleries for artists like J.M.W. Turner.','LON-037',120,180);
INSERT INTO "activities" VALUES('LON-038-A1','Southbank Centre Book Market',4,0.0,'Browse for second-hand books at the bustling market under Waterloo Bridge, open daily.','LON-038',20,40);
INSERT INTO "activities" VALUES('LON-038-A2','Attend a Free Foyer Performance',4,0.0,'Check the schedule for free music, workshops, and performances in the foyer of the Royal Festival Hall.','LON-038',30,60);
INSERT INTO "activities" VALUES('LON-039-A1','SEA LIFE London Aquarium Visit',5,30.0,'Discover a huge collection of global marine life, walk through the shark tunnel, and see penguins and jellyfish.','LON-039',120,150);
INSERT INTO "activities" VALUES('LON-040-A1','The London Dungeon Experience',2,29.5,'A thrilling and scary attraction that walks you through London''s darkest history with live actors and rides. (Not for the faint-hearted)','LON-040',90,110);
INSERT INTO "activities" VALUES('LON-041-A1','Meet the Stars at Madame Tussauds',5,36.0,'Pose with wax figures of your favourite celebrities, historical icons, royalty, and superheroes.','LON-041',120,180);
INSERT INTO "activities" VALUES('LON-042-A1','Feed the Pelicans',5,0.0,'Stroll through this beautiful park and see the famous pelicans being fed daily between 2:30 PM and 3:00 PM.','LON-042',30,45);
INSERT INTO "activities" VALUES('LON-042-A2','View of Buckingham Palace from the Blue Bridge',5,0.0,'Walk to the middle of the Blue Bridge over the lake for a classic, picture-perfect view of Buckingham Palace.','LON-042',15,20);
INSERT INTO "activities" VALUES('LON-043-A1','Climb The Monument',3,5.8,'Climb the 311 spiral steps to the top of Sir Christopher Wren''s column for panoramic views and receive a certificate upon completion.','LON-043',45,60);
INSERT INTO "activities" VALUES('LON-044-A1','Walk and Photograph Colourful Houses',4,0.0,'Wander the charming streets and mews of Notting Hill to see and photograph the iconic pastel-coloured terraced houses.','LON-044',60,90);
INSERT INTO "activities" VALUES('LON-044-A2','Notting Hill Film Locations Tour',3,0.0,'Take a self-guided walk to find famous locations from the film ''Notting Hill'', including the blue door and the travel bookshop.','LON-044',45,60);
INSERT INTO "activities" VALUES('LON-045-A1','Antique Hunting on Portobello Road',3,20.0,'Explore the world''s largest antiques market on a Saturday, browsing for unique treasures and vintage finds. (Cost is estimate for purchase)','LON-045',120,180);
INSERT INTO "activities" VALUES('LON-046-A1','Royal Albert Hall Guided Tour',3,16.5,'Take a fascinating tour of this iconic concert hall, see the auditorium, and maybe even hear musicians rehearsing.','LON-046',60,75);
INSERT INTO "activities" VALUES('LON-046-A2','Attend a Concert or Event',3,50.0,'Experience a live performance, from classical proms to rock concerts, in this legendary venue. (Cost varies wildly)','LON-046',120,180);
INSERT INTO "activities" VALUES('LON-047-A1','Visit the Albert Memorial and Serpentine Galleries',4,0.0,'Admire the ornate Albert Memorial, then visit the two Serpentine Galleries for contemporary art exhibitions.','LON-047',60,90);
INSERT INTO "activities" VALUES('LON-047-A2','Diana Memorial Playground',5,0.0,'Let the kids play in this huge, magical playground inspired by Peter Pan, featuring a giant pirate ship.','LON-047',60,120);
INSERT INTO "activities" VALUES('LON-048-A1','Explore the Design Museum',4,12.0,'Discover the world of contemporary design, from architecture and fashion to graphics and product design. (Cost for paid exhibition)','LON-048',90,150);
INSERT INTO "activities" VALUES('LON-049-A1','See a Play at The Old Vic',2,35.0,'Experience world-class theatre at this iconic, independent London playhouse. (Cost is an estimate for a mid-range seat)','LON-049',150,180);
INSERT INTO "activities" VALUES('LON-050-A1','Visit Saatchi Gallery',3,0.0,'Discover cutting-edge contemporary art by emerging and international artists in a beautiful gallery space. (Some exhibitions may be ticketed)','LON-050',60,120);
INSERT INTO "activities" VALUES('LON-051-A1','Enjoy a Brick Lane Curry',3,20.0,'Experience London''s famous ''curry mile'' by having a meal at one of the many Bangladeshi restaurants.','LON-051',60,90);
INSERT INTO "activities" VALUES('LON-051-A2','Explore Vintage Shops and Street Art',3,0.0,'Hunt for vintage clothing bargains and spot vibrant street art and graffiti down the side streets.','LON-051',90,120);
INSERT INTO "activities" VALUES('LON-052-A1','Street Art Walking Tour',3,0.0,'Take a self-guided tour of Shoreditch''s streets to discover an ever-changing outdoor gallery of work by artists from around the world.','LON-052',90,120);
INSERT INTO "activities" VALUES('LON-052-A2','Browse Independent Boutiques',2,0.0,'Explore the unique and trendy independent shops and boutiques that define Shoreditch''s creative character.','LON-052',60,90);
INSERT INTO "activities" VALUES('LON-053-A1','Explore the Barbican Conservatory',4,0.0,'Visit the hidden tropical oasis on the Barbican''s roof, the second biggest conservatory in London. (Open on select days, booking required)','LON-053',45,60);
INSERT INTO "activities" VALUES('LON-053-A2','Architecture Walk',2,0.0,'Walk the highwalks and admire the unique and controversial Brutalist architecture of the Barbican Estate.','LON-053',30,45);
INSERT INTO "activities" VALUES('LON-054-A1','Journey Through London''s History',4,0.0,'Discover the story of the capital from Roman times to the present day, with reconstructed streets and immersive galleries.','LON-054',120,180);
INSERT INTO "activities" VALUES('LON-055-A1','Winter Ice Skating',5,17.0,'Go ice skating in one of London''s most beautiful settings, the neoclassical courtyard of Somerset House. (Seasonal)','LON-055',60,90);
INSERT INTO "activities" VALUES('LON-055-A2','Summer Series Concert',2,45.0,'Attend an open-air concert in the spectacular courtyard during the annual Summer Series. (Seasonal)','LON-055',120,240);
INSERT INTO "activities" VALUES('LON-056-A1','Visit the Summer Exhibition',3,22.0,'Visit the world''s largest open-submission art show, a fixture of the London summer since 1769.','LON-056',90,150);
INSERT INTO "activities" VALUES('LON-057-A1','Shop for Liberty Fabrics',3,30.0,'Explore the iconic Tudor-revival building and browse its world-famous collection of floral and graphic print fabrics. (Cost estimate for 1m fabric)','LON-057',45,75);
INSERT INTO "activities" VALUES('LON-058-A1','Explore Carnaby Street',3,0.0,'Walk down the famous pedestrianised street, browse the flagship stores and independent boutiques, and see the unique art installations.','LON-058',60,90);
INSERT INTO "activities" VALUES('LON-059-A1','Recreate the Abbey Road Album Cover',4,0.0,'Join fans from around the world to take your photo on the iconic zebra crossing outside the studios. Be careful of traffic!','LON-059',20,40);
INSERT INTO "activities" VALUES('LON-060-A1','Modern Architecture & Public Art Walk',3,0.0,'Explore the Canary Wharf estate, admire the modern skyscrapers, and discover over 75 works of public art.','LON-060',60,90);
INSERT INTO "activities" VALUES('LON-061-A1','Ride the Emirates Air Line Cable Car',5,5.0,'Take a one-way trip across the River Thames for unique aerial views of the Docklands, The O2, and Greenwich Peninsula.','LON-061',20,30);
INSERT INTO "activities" VALUES('LON-062-A1','Up at The O2 - Climb the Dome',3,35.0,'Take an exhilarating guided climb over the roof of The O2 for incredible views of the city. (Ages 8+)','LON-062',90,90);
INSERT INTO "activities" VALUES('LON-063-A1','Walk to Parliament Hill Viewpoint',5,0.0,'Enjoy a walk through the wild parkland of Hampstead Heath and climb Parliament Hill for a famous, protected view of the London skyline.','LON-063',60,90);
INSERT INTO "activities" VALUES('LON-063-A2','Swim in the Hampstead Ponds',2,4.5,'Take a dip in one of the famous open-air swimming ponds for a bracing and uniquely London experience. (Seasonal, for strong swimmers)','LON-063',60,120);
INSERT INTO "activities" VALUES('LON-064-A1','Wembley Stadium Tour',4,24.0,'Go behind the scenes at the home of English football, visit the changing rooms, and walk through the players'' tunnel.','LON-064',75,90);
INSERT INTO "activities" VALUES('LON-065-A1','Twickenham Stadium Tour & World Rugby Museum',4,27.0,'Visit the home of England Rugby, see the pitch from the Royal Box, and explore the ultimate collection of rugby memorabilia.','LON-065',120,150);
INSERT INTO "activities" VALUES('LON-066-A1','Wimbledon Lawn Tennis Museum Visit',4,15.0,'Explore the history of tennis from its origins to the present day and get a peek at the famous Centre Court.','LON-066',90,120);
INSERT INTO "activities" VALUES('LON-067-A1','Explore the London Transport Museum',5,24.0,'Climb aboard historic buses and trains, and explore the link between transport and the growth of modern London. Great for families.','LON-067',120,180);
INSERT INTO "activities" VALUES('LON-068-A1','View of Downing Street',3,0.0,'Look through the security gates on Whitehall to catch a glimpse of the famous black door of Number 10, the Prime Minister''s residence.','LON-068',10,20);
INSERT INTO "activities" VALUES('LON-069-A1','Pay Respects at The Cenotaph',3,0.0,'Take a moment to view the United Kingdom''s primary national war memorial on the route between Parliament and Trafalgar Square.','LON-069',5,15);
INSERT INTO "activities" VALUES('LON-070-A1','Watch the Changing of the King''s Life Guard',5,0.0,'See the household cavalry change guard in a daily ceremony that is smaller but just as impressive as the one at Buckingham Palace.','LON-070',30,45);
INSERT INTO "activities" VALUES('LON-071-A1','Admire The Gherkin from the outside',3,0.0,'Take a walk around the base of one of London''s most recognizable contemporary skyscrapers and appreciate its unique design.','LON-071',10,20);
INSERT INTO "activities" VALUES('LON-072-A1','Explore Leadenhall Market',4,0.0,'Wander through the ornate and beautiful covered Victorian market, admiring the architecture and browsing the boutique shops.','LON-072',30,60);
INSERT INTO "activities" VALUES('LON-072-A2','Find Harry Potter''s Diagon Alley Entrance',5,0.0,'Seek out the blue door in the market that was used as the entrance to the Leaky Cauldron in the first Harry Potter film.','LON-072',10,15);
INSERT INTO "activities" VALUES('LON-073-A1','Relax in the Sky Garden',4,0.0,'Enjoy panoramic city views from London''s highest public garden. Booking a free ticket in advance is essential.','LON-073',45,90);
INSERT INTO "activities" VALUES('LON-074-A1','Walk Across the Millennium Bridge',5,0.0,'Stroll across the pedestrian bridge for fantastic, direct views of St. Paul''s Cathedral at one end and Tate Modern at the other.','LON-074',15,25);
INSERT INTO "activities" VALUES('LON-075-A1','Canal Boat Trip to Camden',5,14.0,'Take a scenic waterbus ride along Regent''s Canal from the picturesque Little Venice to the lively Camden Lock.','LON-075',50,60);
INSERT INTO "activities" VALUES('LON-075-A2','Waterside Cafe Stop',4,8.0,'Relax at one of the charming cafes overlooking the canal junction and watch the narrowboats go by.','LON-075',30,45);
INSERT INTO "activities" VALUES('LON-076-A1','Platform 9¾ Photo Op',5,0.0,'Visit the Harry Potter photo opportunity spot with a luggage trolley disappearing into the wall. Be prepared for long queues.','LON-076',20,60);
INSERT INTO "activities" VALUES('LON-077-A1','Explore the Wellcome Collection',3,0.0,'Visit the ''free destination for the incurably curious'' and explore fascinating exhibitions on health, life, and our place in the world.','LON-077',90,120);
INSERT INTO "activities" VALUES('LON-078-A1','See the Treasures of the British Library',4,0.0,'Visit the Sir John Ritblat Gallery to see world-famous items like the Magna Carta, Shakespeare''s First Folio, and original Beatles lyrics.','LON-078',45,75);
INSERT INTO "activities" VALUES('LON-079-A1','Pre-Theatre Dinner in Soho',3,30.0,'Soak up the vibrant atmosphere and grab a meal from one of the hundreds of diverse restaurants before a West End show.','LON-079',60,90);
INSERT INTO "activities" VALUES('LON-079-A2','Explore Soho''s Hidden Alleys',2,0.0,'Wander through the narrow streets and passages of Soho to discover its history, quirky shops, and unique character.','LON-079',45,60);
INSERT INTO "activities" VALUES('LON-080-A1','Authentic Dim Sum Lunch',4,20.0,'Explore the bustling streets of Chinatown and enjoy a traditional dim sum meal at one of the many popular restaurants.','LON-080',60,75);
INSERT INTO "activities" VALUES('LON-080-A2','Browse for Treats at a Chinese Bakery',5,5.0,'Step into one of the local bakeries and try a delicious and authentic treat like a custard bun or a sweet pastry.','LON-080',15,20);
INSERT INTO "activities" VALUES('LON-081-A1','Visit The Royal Mews',4,15.0,'See the spectacular Gold State Coach and other royal carriages in one of the finest working stables in existence.','LON-081',60,90);
INSERT INTO "activities" VALUES('LON-082-A1','Visit The Queen''s Gallery Exhibition',2,17.0,'View a changing selection of magnificent paintings, drawings, and treasures from the Royal Collection.','LON-082',60,90);
INSERT INTO "activities" VALUES('LON-083-A1','Explore Apsley House',2,12.5,'Visit ''Number 1, London'', the home of the first Duke of Wellington, and see his stunning collection of art and treasures.','LON-083',90,120);
INSERT INTO "activities" VALUES('LON-084-A1','Explore all nine decks of HMS Belfast',4,25.0,'Climb aboard the historic Royal Navy warship and discover what life was like at sea, from the engine rooms to the flag deck.','LON-084',120,180);
INSERT INTO "activities" VALUES('LON-085-A1','Visit the Painted Hall',3,13.5,'Marvel at ''Britain''s Sistine Chapel'', the spectacular baroque Painted Hall at the heart of the Maritime Greenwich UNESCO World Heritage Site.','LON-085',60,90);
INSERT INTO "activities" VALUES('LON-086-A1','National Maritime Museum Visit',5,0.0,'Explore Britain''s epic relationship with the sea, see Nelson''s coat from the Battle of Trafalgar, and let kids run wild in the AHOY! gallery.','LON-086',120,180);
INSERT INTO "activities" VALUES('LON-087-A1','Ride The Slide at the ArcelorMittal Orbit',4,16.75,'Take in the views from the top of the UK''s tallest sculpture before riding the world''s longest and tallest tunnel slide. (Height/age restrictions apply)','LON-087',30,45);
INSERT INTO "activities" VALUES('LON-088-A1','Explore Queen Elizabeth Olympic Park',5,0.0,'Walk or cycle through the parklands, see the iconic 2012 Olympic venues, and enjoy the playgrounds and fountains.','LON-088',90,180);
INSERT INTO "activities" VALUES('LON-088-A2','Swim at the London Aquatics Centre',5,6.0,'Take a swim in the spectacular Zaha Hadid-designed pool that hosted the 2012 Olympic swimming events.','LON-088',60,90);
INSERT INTO "activities" VALUES('LON-089-A1','Deer Spotting in Richmond Park',5,0.0,'Go for a long walk or cycle in London''s largest Royal Park and look for the herds of wild red and fallow deer. Keep a respectful distance.','LON-089',120,240);
INSERT INTO "activities" VALUES('LON-089-A2','Visit Isabella Plantation',5,0.0,'Explore the stunning 40-acre woodland garden, especially in late spring when the azaleas and rhododendrons are in full bloom.','LON-089',60,90);
INSERT INTO "activities" VALUES('LON-090-A1','Sunday Morning Flower Market',3,15.0,'Experience the vibrant sights, sounds, and smells of this bustling flower market. Arrive early to avoid the biggest crowds. (Cost is estimate for purchase)','LON-090',60,90);
INSERT INTO "activities" VALUES('LON-091-A1','Visit The Garden at 120',4,0.0,'Enjoy exceptional free views of the surrounding skyscrapers from this public rooftop garden in the heart of the City. No booking required.','LON-091',30,45);
INSERT INTO "activities" VALUES('LON-092-A1','Visit the Memorial to Heroic Self-Sacrifice',3,0.0,'Take a quiet moment in this peaceful park to read the moving memorial plaques dedicated to ordinary people who died saving others.','LON-092',15,30);
INSERT INTO "activities" VALUES('LON-093-A1','Explore Leighton House Museum',2,11.0,'Visit the opulent former home and studio of Victorian artist Frederic, Lord Leighton, and marvel at its stunning Arab Hall.','LON-093',60,90);
INSERT INTO "activities" VALUES('LON-094-A1','Visit Chelsea Physic Garden',3,13.5,'Discover a tranquil, hidden oasis on the edge of the Thames, home to London''s oldest botanic garden and around 5,000 medicinal plants.','LON-094',90,120);
INSERT INTO "activities" VALUES('LON-095-A1','The Courtauld Gallery Visit',2,9.0,'See a magnificent collection of art, including world-famous Impressionist and Post-Impressionist masterpieces by Manet, Van Gogh, and Cézanne.','LON-095',60,90);
INSERT INTO "activities" VALUES('LON-096-A1','Explore Southwark Cathedral',3,0.0,'Visit London''s oldest Gothic church, which has links to Shakespeare and Charles Dickens. (Donations encouraged)','LON-096',30,60);
INSERT INTO "activities" VALUES('LON-097-A1','Attend a Gig at The Roundhouse',1,40.0,'See a concert at this legendary circular venue in Camden, known for its incredible atmosphere and diverse line-up of artists. (Cost varies)','LON-097',180,240);
INSERT INTO "activities" VALUES('LON-098-A1','Late Show at Ronnie Scott''s',1,15.0,'Experience the intimate atmosphere of one of the world''s most famous jazz clubs for their renowned late late show.','LON-098',90,120);
INSERT INTO "activities" VALUES('LON-099-A1','Visit The Faraday Museum',3,0.0,'Explore Michael Faraday''s magnetic laboratory and discover 200 years of science history at the Royal Institution. (Open weekdays)','LON-099',45,60);
INSERT INTO "activities" VALUES('LON-100-A1','Dennis Severs'' House ''Still-life Drama'' Tour',1,20.0,'Take a unique, silent tour through an atmospheric time capsule of Spitalfields life, designed to be experienced by your senses. (Booking essential)','LON-100',50,60);
INSERT INTO "activities" VALUES('LON-101-A1','Highgate Cemetery West Guided Tour',1,15.0,'Take a guided tour of the atmospheric West Cemetery to see the Egyptian Avenue, Circle of Lebanon, and elaborate Gothic tombs. (Booking essential)','LON-101',70,70);
INSERT INTO "activities" VALUES('LON-101-A2','Highgate Cemetery East Self-Guided Visit',2,4.5,'Explore the East Cemetery at your own pace and find the graves of famous residents, including Karl Marx and George Eliot.','LON-101',45,90);
INSERT INTO "activities" VALUES('LON-102-A1','Walk in Epping Forest',5,0.0,'Escape the city and enjoy a long walk or cycle through the ancient woodland, following one of the many marked trails.','LON-102',120,240);
CREATE TABLE "locations" (
"sight_id" TEXT,
  "name" TEXT,
  "category" TEXT,
  "description" TEXT
);
INSERT INTO "locations" VALUES('LON-001','The British Museum','Museum','A world-famous museum showcasing two million years of human history and culture, featuring iconic artifacts like the Rosetta Stone.');
INSERT INTO "locations" VALUES('LON-002','Tower of London','Historic Landmark','A historic castle on the River Thames, home to the Crown Jewels, legendary Yeoman Warders, and tales of royal intrigue.');
INSERT INTO "locations" VALUES('LON-003','The London Eye','Modern Attraction','A giant cantilevered observation wheel on the South Bank, offering breathtaking 360-degree views of the city.');
INSERT INTO "locations" VALUES('LON-004','Buckingham Palace','Royal Palace','The official residence and administrative headquarters of the monarch of the United Kingdom.');
INSERT INTO "locations" VALUES('LON-005','Hyde Park','Royal Park','One of London''s largest and most famous parks, home to the Serpentine Lake, Speaker''s Corner, and seasonal events.');
INSERT INTO "locations" VALUES('LON-006','Westminster Abbey','Historic Landmark','A magnificent Gothic abbey church that has been the site of every royal coronation since 1066.');
INSERT INTO "locations" VALUES('LON-007','Houses of Parliament','Government Building','The seat of the UK Parliament, an iconic neo-Gothic building featuring the famous clock tower, Big Ben.');
INSERT INTO "locations" VALUES('LON-008','Tate Modern','Art Gallery','Britain''s national gallery of international modern art, housed in the former Bankside Power Station.');
INSERT INTO "locations" VALUES('LON-009','St. Paul''s Cathedral','Historic Landmark','An Anglican cathedral with a world-famous dome that has dominated the London skyline for 300 years.');
INSERT INTO "locations" VALUES('LON-010','Natural History Museum','Museum','A leading science research centre and museum exhibiting a vast range of specimens, including its famous dinosaur skeletons.');
INSERT INTO "locations" VALUES('LON-011','Victoria and Albert Museum (V&A)','Museum','The world''s leading museum of art, design, and performance, housing a permanent collection of over 2.3 million objects.');
INSERT INTO "locations" VALUES('LON-012','Science Museum','Museum','A major museum on Exhibition Road showcasing world-changing scientific and technological advancements.');
INSERT INTO "locations" VALUES('LON-013','The National Gallery','Art Gallery','Located in Trafalgar Square, this gallery houses a rich collection of over 2,300 paintings dating from the mid-13th century to 1900.');
INSERT INTO "locations" VALUES('LON-014','Tower Bridge','Historic Landmark','An iconic combined bascule and suspension bridge, famous for its glass walkway and engine rooms.');
INSERT INTO "locations" VALUES('LON-015','Shakespeare''s Globe','Theatre','A realistic reconstruction of the Globe Theatre, an Elizabethan playhouse for which William Shakespeare wrote his plays.');
INSERT INTO "locations" VALUES('LON-016','The Shard','Modern Attraction','Western Europe''s tallest building, offering stunning panoramic views from its observation deck, ''The View from The Shard''.');
INSERT INTO "locations" VALUES('LON-017','Borough Market','Market','London''s oldest and most renowned food market, offering a vibrant mix of fresh produce and gourmet street food.');
INSERT INTO "locations" VALUES('LON-018','Covent Garden','Neighborhood','A vibrant shopping and entertainment hub in London''s West End, famous for its street performers and upscale boutiques.');
INSERT INTO "locations" VALUES('LON-019','Kensington Palace','Royal Palace','A royal residence set in Kensington Gardens, and the birthplace of Queen Victoria.');
INSERT INTO "locations" VALUES('LON-020','Regent''s Park','Royal Park','A beautiful park featuring formal gardens, a boating lake, and home to London Zoo and an Open Air Theatre.');
INSERT INTO "locations" VALUES('LON-021','Camden Market','Market','An eclectic and diverse market known for its alternative fashion, global street food, and unique crafts.');
INSERT INTO "locations" VALUES('LON-022','Greenwich Park','Royal Park','A former hunting park offering stunning views of the city, home to the Prime Meridian Line and the Royal Observatory.');
INSERT INTO "locations" VALUES('LON-023','Royal Observatory Greenwich','Museum','The home of Greenwich Mean Time (GMT), where visitors can stand on the historic Prime Meridian of the world.');
INSERT INTO "locations" VALUES('LON-024','Cutty Sark','Historic Landmark','The world''s sole surviving tea clipper, now an award-winning museum ship in Greenwich.');
INSERT INTO "locations" VALUES('LON-025','Trafalgar Square','Landmark','A famous public square featuring Nelson''s Column, iconic lion statues, and the National Gallery.');
INSERT INTO "locations" VALUES('LON-026','Piccadilly Circus','Landmark','A famous road junction and public space, known for its huge video displays and neon signs.');
INSERT INTO "locations" VALUES('LON-027','Churchill War Rooms','Museum','The secret underground headquarters where Winston Churchill and his government directed WWII.');
INSERT INTO "locations" VALUES('LON-028','Hampton Court Palace','Royal Palace','A magnificent Tudor palace once home to Henry VIII, featuring a famous maze and beautiful gardens.');
INSERT INTO "locations" VALUES('LON-029','Kew Gardens','Garden','The Royal Botanic Gardens, a UNESCO World Heritage site with vast landscapes and iconic Victorian glasshouses.');
INSERT INTO "locations" VALUES('LON-030','London Zoo','Attraction','The world''s oldest scientific zoo, located in Regent''s Park, housing thousands of animals.');
INSERT INTO "locations" VALUES('LON-031','The National Portrait Gallery','Art Gallery','Houses a collection of portraits of historically important and famous British people.');
INSERT INTO "locations" VALUES('LON-032','Imperial War Museum London','Museum','A museum that tells the story of people''s experiences of modern war from WWI to conflicts today.');
INSERT INTO "locations" VALUES('LON-033','The Wallace Collection','Art Gallery','A national museum in a historic London townhouse displaying fine and decorative arts from the 15th to the 19th centuries.');
INSERT INTO "locations" VALUES('LON-034','Sir John Soane''s Museum','Museum','The extraordinary house of the neo-classical architect Sir John Soane, left as it was at the time of his death.');
INSERT INTO "locations" VALUES('LON-035','Harrods','Shopping','One of the world''s most famous luxury department stores, known for its opulent food halls and high-end fashion.');
INSERT INTO "locations" VALUES('LON-036','The Globe Theatre Tour & Exhibition','Tour','An expertly guided tour exploring the story of the iconic Globe Theatre and the London of Shakespeare''s time.');
INSERT INTO "locations" VALUES('LON-037','Tate Britain','Art Gallery','The home of British art from 1500 to the present day, featuring works by Turner, Constable, and Hockney.');
INSERT INTO "locations" VALUES('LON-038','Southbank Centre','Arts Venue','A complex of artistic venues on the South Bank, including the Royal Festival Hall, Queen Elizabeth Hall, and Hayward Gallery.');
INSERT INTO "locations" VALUES('LON-039','SEA LIFE London Aquarium','Attraction','Home to one of Europe''s largest collections of global marine life, located on the South Bank.');
INSERT INTO "locations" VALUES('LON-040','The London Dungeon','Attraction','A thrilling attraction that walks you through 1000 years of London''s darkest history with live actors and rides.');
INSERT INTO "locations" VALUES('LON-041','Madame Tussauds London','Attraction','A world-famous wax museum featuring lifelike figures of celebrities, historical icons, and royalty.');
INSERT INTO "locations" VALUES('LON-042','St. James''s Park','Royal Park','A tranquil park in the heart of ceremonial London, famous for its pelicans and views of Buckingham Palace.');
INSERT INTO "locations" VALUES('LON-043','The Monument','Historic Landmark','A 202-foot column designed by Sir Christopher Wren to commemorate the Great Fire of London.');
INSERT INTO "locations" VALUES('LON-044','Notting Hill','Neighborhood','A vibrant and affluent district known for its colourful terraced houses and the famous Portobello Road Market.');
INSERT INTO "locations" VALUES('LON-045','Portobello Road Market','Market','The world''s largest antiques market, also featuring fashion, food, and second-hand goods.');
INSERT INTO "locations" VALUES('LON-046','Royal Albert Hall','Music Venue','A prestigious concert hall, best known for holding the annual Proms concerts.');
INSERT INTO "locations" VALUES('LON-047','Kensington Gardens','Royal Park','A beautiful park adjoining Hyde Park, home to Kensington Palace, the Albert Memorial, and the Serpentine Galleries.');
INSERT INTO "locations" VALUES('LON-048','Design Museum','Museum','A museum devoted to contemporary design in every form, from architecture and fashion to graphics and product design.');
INSERT INTO "locations" VALUES('LON-049','The Old Vic','Theatre','A 200-year-old independent, not-for-profit theatre in Waterloo.');
INSERT INTO "locations" VALUES('LON-050','Saatchi Gallery','Art Gallery','A contemporary art gallery in Chelsea, known for showcasing work by young and emerging artists.');
INSERT INTO "locations" VALUES('LON-051','Brick Lane','Neighborhood','Famous for its curry houses, vintage shops, vibrant street art, and bustling Sunday market.');
INSERT INTO "locations" VALUES('LON-052','Shoreditch','Neighborhood','A trendy and creative hub known for its street art, independent boutiques, and vibrant nightlife.');
INSERT INTO "locations" VALUES('LON-053','The Barbican Centre','Arts Venue','A world-class performing arts centre in a notable example of Brutalist architecture, featuring a concert hall, theatres, and a conservatory.');
INSERT INTO "locations" VALUES('LON-054','Museum of London','Museum','Tells the story of the capital from its first settlers to modern times.');
INSERT INTO "locations" VALUES('LON-055','Somerset House','Arts Venue','A major arts and cultural centre with a spectacular neoclassical courtyard, hosting exhibitions, concerts, and an ice rink in winter.');
INSERT INTO "locations" VALUES('LON-056','Royal Academy of Arts','Art Gallery','An independent, privately funded institution led by eminent artists and architects, hosting major exhibitions.');
INSERT INTO "locations" VALUES('LON-057','Liberty London','Shopping','A luxury department store in a beautiful Tudor-revival building, famous for its floral and graphic prints.');
INSERT INTO "locations" VALUES('LON-058','Carnaby Street','Shopping','A famous pedestrianised shopping street in Soho, known as the birthplace of fashion and cultural revolutions in the 1960s.');
INSERT INTO "locations" VALUES('LON-059','Abbey Road Studios','Landmark','The most famous recording studio in the world, known for its association with The Beatles. The zebra crossing outside is an iconic photo spot.');
INSERT INTO "locations" VALUES('LON-060','Canary Wharf','Neighborhood','A major business district in East London, known for its modern skyscrapers, public art, and extensive shopping centre.');
INSERT INTO "locations" VALUES('LON-061','Emirates Air Line Cable Car','Attraction','A cable car link across the River Thames, providing unique aerial views of the Docklands and Greenwich Peninsula.');
INSERT INTO "locations" VALUES('LON-062','The O2','Music Venue','A massive entertainment district inside the former Millennium Dome, including an arena, cinema, restaurants, and an urban mountaineering experience.');
INSERT INTO "locations" VALUES('LON-063','Hampstead Heath','Park','A large, ancient parkland with swimming ponds, woodlands, and one of the highest points in London at Parliament Hill.');
INSERT INTO "locations" VALUES('LON-064','Wembley Stadium','Sports Venue','The iconic national stadium of England, hosting major football matches and music concerts.');
INSERT INTO "locations" VALUES('LON-065','Twickenham Stadium','Sports Venue','The home of England Rugby, the largest dedicated rugby union venue in the world.');
INSERT INTO "locations" VALUES('LON-066','Wimbledon Lawn Tennis Museum','Museum','Explore the history of ''The Championships'' at the home of tennis, with access to Centre Court.');
INSERT INTO "locations" VALUES('LON-067','London Transport Museum','Museum','Located in Covent Garden, this museum explores the link between transport and the growth of modern London.');
INSERT INTO "locations" VALUES('LON-068','Downing Street','Government Building','The famous street containing the official residence and office of the Prime Minister of the United Kingdom at Number 10.');
INSERT INTO "locations" VALUES('LON-069','The Cenotaph','Historic Landmark','The United Kingdom''s primary national war memorial, located on Whitehall.');
INSERT INTO "locations" VALUES('LON-070','Horse Guards Parade','Landmark','A large parade ground off Whitehall, which is the site of the annual Trooping the Colour ceremony.');
INSERT INTO "locations" VALUES('LON-071','The Gherkin (30 St Mary Axe)','Modern Attraction','One of London''s most recognizable contemporary skyscrapers in the financial district.');
INSERT INTO "locations" VALUES('LON-072','Leadenhall Market','Market','A beautiful covered Victorian market, famous for its ornate architecture and as a filming location for Harry Potter.');
INSERT INTO "locations" VALUES('LON-073','Sky Garden','Modern Attraction','London''s highest public garden, offering panoramic views and lush greenery from the top of the ''Walkie Talkie'' building.');
INSERT INTO "locations" VALUES('LON-074','Millennium Bridge','Landmark','A steel suspension bridge for pedestrians crossing the River Thames, linking the Tate Modern with St. Paul''s Cathedral.');
INSERT INTO "locations" VALUES('LON-075','Little Venice','Neighborhood','A picturesque canal area where the Grand Union and Regent''s Canals meet, known for its colourful narrowboats and waterside cafes.');
INSERT INTO "locations" VALUES('LON-076','King''s Cross Station','Landmark','A major railway terminus famous for its beautifully restored Victorian architecture and the fictional Platform 9¾ from Harry Potter.');
INSERT INTO "locations" VALUES('LON-077','Wellcome Collection','Museum','A free museum and library that explores health and human experience through science, art, and medicine.');
INSERT INTO "locations" VALUES('LON-078','The British Library','Library','The national library of the United Kingdom and one of the world''s greatest, holding treasures like the Magna Carta and original Beatles lyrics.');
INSERT INTO "locations" VALUES('LON-079','Soho','Neighborhood','A vibrant area in the West End, packed with theatres, restaurants, pubs, and a lively nightlife.');
INSERT INTO "locations" VALUES('LON-080','Chinatown','Neighborhood','A bustling neighborhood with ornate gates, traditional Chinese restaurants, bakeries, and supermarkets.');
INSERT INTO "locations" VALUES('LON-081','The Royal Mews','Museum','A working royal stables responsible for all road travel arrangements for The King, housing the magnificent Gold State Coach.');
INSERT INTO "locations" VALUES('LON-082','The Queen''s Gallery','Art Gallery','A public art gallery at Buckingham Palace, exhibiting works of art from the Royal Collection on a rotating basis.');
INSERT INTO "locations" VALUES('LON-083','Apsley House','Museum','The London townhouse of the Dukes of Wellington, also known as ''Number 1, London'', featuring a stunning art collection.');
INSERT INTO "locations" VALUES('LON-084','HMS Belfast','Museum','A historic Royal Navy light cruiser, now a museum ship permanently moored on the River Thames.');
INSERT INTO "locations" VALUES('LON-085','Old Royal Naval College','Historic Landmark','A stunning architectural centrepiece of Maritime Greenwich, designed by Sir Christopher Wren, featuring the Painted Hall.');
INSERT INTO "locations" VALUES('LON-086','National Maritime Museum','Museum','The world''s largest maritime museum, filled with inspirational stories of discovery and adventure at sea.');
INSERT INTO "locations" VALUES('LON-087','ArcelorMittal Orbit','Modern Attraction','The UK''s tallest sculpture, located in Queen Elizabeth Olympic Park, featuring the world''s longest and tallest tunnel slide.');
INSERT INTO "locations" VALUES('LON-088','Queen Elizabeth Olympic Park','Park','A sporting complex and public park built for the 2012 Summer Olympics, featuring iconic venues and parklands.');
INSERT INTO "locations" VALUES('LON-089','Richmond Park','Royal Park','The largest of London''s Royal Parks, famous for its wide-open spaces, ancient trees, and herds of red and fallow deer.');
INSERT INTO "locations" VALUES('LON-090','Columbia Road Flower Market','Market','A vibrant and fragrant street market in East London, transforming a Victorian street into an oasis of foliage and flowers every Sunday.');
INSERT INTO "locations" VALUES('LON-091','The Garden at 120','Garden','A free public rooftop space and garden in the City of London, offering exceptional views of the surrounding skyscrapers.');
INSERT INTO "locations" VALUES('LON-092','Postman''s Park','Park','A quiet park home to the Memorial to Heroic Self-Sacrifice, a moving wall of plaques to ordinary people who died saving others.');
INSERT INTO "locations" VALUES('LON-093','Leighton House Museum','Museum','The former home and studio of the Victorian artist Frederic, Lord Leighton, famous for its opulent Arab Hall.');
INSERT INTO "locations" VALUES('LON-094','Chelsea Physic Garden','Garden','London''s oldest botanic garden, a hidden green oasis housing a unique collection of medicinal and useful plants.');
INSERT INTO "locations" VALUES('LON-095','The Courtauld Gallery','Art Gallery','Houses the art collection of the Courtauld Institute of Art, best known for its collection of Impressionist and Post-Impressionist paintings.');
INSERT INTO "locations" VALUES('LON-096','Southwark Cathedral','Historic Landmark','London''s oldest Gothic church, located at the southern end of London Bridge, with a history stretching back over 1,000 years.');
INSERT INTO "locations" VALUES('LON-097','The Roundhouse','Music Venue','A legendary performing arts and concert venue in Camden Town, housed in a former railway engine shed.');
INSERT INTO "locations" VALUES('LON-098','Ronnie Scott''s Jazz Club','Music Venue','One of the world''s most famous jazz clubs, located in the heart of Soho, hosting legendary musicians since 1959.');
INSERT INTO "locations" VALUES('LON-099','The Faraday Museum','Museum','Located at the Royal Institution, this museum showcases the history of science and the groundbreaking experiments of Michael Faraday.');
INSERT INTO "locations" VALUES('LON-100','Dennis Severs'' House','Museum','A unique ''still-life drama'' in a Spitalfields townhouse, offering an intimate and atmospheric time capsule of life from the 18th to the early 20th century.');
INSERT INTO "locations" VALUES('LON-101','Highgate Cemetery','Historic Landmark','A historic cemetery known for its elaborate Gothic tombs, winding paths, and as the final resting place of Karl Marx.');
INSERT INTO "locations" VALUES('LON-102','Epping Forest','Park','A vast area of ancient woodland on the edge of London, offering miles of walking and cycling trails.');
COMMIT;
